-- ============================================================================
-- Auditorías 5S Escorial — datos semilla (catálogos + rúbricas S1-S5)
-- Generado automáticamente desde gen_imprimible.py / gen_imprimible_panol_oficina.py
-- ============================================================================

-- 1. Áreas / sectores organizacionales (clasificación general, Screen 1)
INSERT INTO areas (id, nombre, orden) VALUES
(1, 'Administración', 1),
(2, 'Industria', 2),
(3, 'Supply Chain', 3),
(4, 'Calidad', 4),
(5, 'Postventa', 5),
(6, 'Proyectos', 6);

INSERT INTO sectores (area_id, nombre, orden) VALUES
(1, 'Sistema', 1),
(1, 'Recursos Humanos', 2),
(1, 'Administración', 3),
(2, 'Producción', 1),
(2, 'Mantenimiento', 2),
(2, 'Mejora Continua', 3),
(3, 'Almacén', 1),
(3, 'Expedición', 2),
(3, 'Compras', 3),
(4, 'Calidad', 1),
(4, 'Seguridad', 2),
(5, 'Call Center', 1),
(5, 'Servicio Técnico', 2),
(5, 'Producto', 3),
(6, 'Proyectos', 1),
(6, 'Herrería', 2);

-- 2. Plantas
INSERT INTO plantas (id, nombre, orden) VALUES
(1, '25 de Mayo', 1),
(2, 'Suipacha', 2);

-- UET de Producción (Suipacha, planta_id=2)
INSERT INTO uets (planta_id, nombre, orden) VALUES
(2, 'UET 1', 1),
(2, 'UET 2', 2),
(2, 'UET 3', 3),
(2, 'UET 4', 4),
(2, 'UET 5', 5);

-- Sectores productivos de Suipacha (planta_id=2) + Mantenimiento (Taller / Pañol-Depósito)
INSERT INTO uet_sectores (planta_id, nombre, orden) VALUES
(2, 'LC06/Laser', 1),
(2, 'Circuito de manijas', 2),
(2, 'EP04', 3),
(2, 'Prensas y Omera', 4),
(2, 'Circuito de camisas', 5),
(2, 'Cabina de Pintura', 6),
(2, 'Horno de Pirolisis', 7),
(2, 'Armado Gas', 8),
(2, 'Armado Eléctrico', 9),
(2, 'Calefones', 10),
(2, 'Línea 1 Soldadura', 11),
(2, 'Línea 2 Soldadura', 12),
(2, 'Gema', 13),
(2, 'Línea 1 Cocinas', 14),
(2, 'Línea 2 Cocinas', 15),
(2, 'Línea 3 Cocinas', 16),
(2, 'Enlozado', 17),
(2, 'Estampado', 18),
(2, 'Corte', 19),
(2, 'Taller', 20),
(2, 'Pañol/Depósito', 21);

-- Sectores de 25 de Mayo (planta_id=1) — por ahora solo Mantenimiento; el resto lo define Diego más adelante
INSERT INTO uet_sectores (planta_id, nombre, orden) VALUES
(1, 'Taller', 1),
(1, 'Pañol/Depósito', 2);

-- 3. Rúbricas S1-S5 por tipo de auditoría
-- 3a. Rubric: PLANTA
INSERT INTO rubric_categories (audit_type, tag, label, sub, orden) VALUES ('planta', 'S1', 'S1 - Clasificar', 'Separar innecesarios', 1);
INSERT INTO rubric_items (category_id, nombre, criterio_0, criterio_1, criterio_3, criterio_5, orden) SELECT id, 'Maquinas o equipos innecesarios', 'El área nunca ha sido despejada de máquinas y equipos innecesarios', 'Hay algunas máquinas y equipos innecesarios en el área', 'Hay algunas máquinas y equipos innecesarios en el área, pero cuentan con plan de retiro', 'Sólo están las maquinas y equipos necesarios en el área', 1 FROM rubric_categories WHERE audit_type='planta' AND tag='S1';
INSERT INTO rubric_items (category_id, nombre, criterio_0, criterio_1, criterio_3, criterio_5, orden) SELECT id, 'Materiales, inventario, o insumos innecesarios en el área', 'El área nunca ha sido despejada de materiales, inventario o insumos innecesarios', 'Hay algunos materiales, inventarios o insumos innecesarios sin identificar o superan el máximo', 'Raramente se encuentran materiales, inventarios o insumos innecesarios en el área', 'Sólo está el material, inventario e insumos necesario en el área', 2 FROM rubric_categories WHERE audit_type='planta' AND tag='S1';
INSERT INTO rubric_items (category_id, nombre, criterio_0, criterio_1, criterio_3, criterio_5, orden) SELECT id, 'Herramientas o utensilios innecesarios', 'El área nunca ha sido despejada de herramientas o utensilios innecesarios', 'Hay herramientas o utensilios innecesarios en el área.', 'Hay herramientas o utensilios innecesarios en el área, pero cuentan con plan para su retiro.', 'Sólo están las herramientas y utensilios necesarios en el área.', 3 FROM rubric_categories WHERE audit_type='planta' AND tag='S1';
INSERT INTO rubric_items (category_id, nombre, criterio_0, criterio_1, criterio_3, criterio_5, orden) SELECT id, 'Objetos Personales, materiales de comida, carpetas, hojas, etc.', 'Se encuentran mas de 10 cosas innecesarias', 'Se encuentra menos de 10 de estas cosas innecesarias', 'Se encuentra menos de 3 de estas cosas innecesarias', 'No se encuentra ninguna cosa innecesaria', 4 FROM rubric_categories WHERE audit_type='planta' AND tag='S1';
INSERT INTO rubric_categories (audit_type, tag, label, sub, orden) VALUES ('planta', 'S2', 'S2 - Ordenar', 'Ubicación necesarios e identificar', 2);
INSERT INTO rubric_items (category_id, nombre, criterio_0, criterio_1, criterio_3, criterio_5, orden) SELECT id, 'Herramientas, Maquinas o equipos.', 'Frecuentemente los operadores caminan largas distancias para buscar herramientas, maquinas y equipos', 'A veces los operadores deben dejar las estaciones de trabajo para buscar herramientas, maquinas y equipos.', 'Las herramientas y equipos más requeridos se encuentran ubicados cerca de los operadores e identificados.', 'Todas las herramientas y equipos se encuentran al alcance de los operadores y debidamente identificados.', 1 FROM rubric_categories WHERE audit_type='planta' AND tag='S2';
INSERT INTO rubric_items (category_id, nombre, criterio_0, criterio_1, criterio_3, criterio_5, orden) SELECT id, 'Materiales, inventario, o insumos en el área', 'Los operadores siempre tienen que buscar materiales, inventarios, etc.', 'Materiales, inventarios tienen su lugar definido pero sin identificación visual.', 'Mas de 5 Materiales, inventarios tienen su lugar definido con identificación visual, pero hay mas para definir su identificación.', 'Todos los Materiales, inventarios tienen su lugar definido con identificación visual, y los prioritarios con sistema de Max y Min.', 2 FROM rubric_categories WHERE audit_type='planta' AND tag='S2';
INSERT INTO rubric_items (category_id, nombre, criterio_0, criterio_1, criterio_3, criterio_5, orden) SELECT id, 'Pasillos & Estaciones de Trabajo', 'No existen líneas para marcar los pasillos y las áreas de trabajo', 'Existen algunas líneas para marcar los pasillos pero hay otras líneas marcadas anteriormente que no corresponden.', 'Existen algunas líneas para marcar los pasillos', 'Todos los pasillos y áreas de trabajo están claramente marcadas e identificadas', 3 FROM rubric_categories WHERE audit_type='planta' AND tag='S2';
INSERT INTO rubric_items (category_id, nombre, criterio_0, criterio_1, criterio_3, criterio_5, orden) SELECT id, '¿El área está diseñada para usar herramientas y devolverlas a su lugar fácilmente?', 'Ninguna herramienta', 'Mas de 5 herramientas', 'Mas de 10 herramientas', 'Todas las herramientas.', 4 FROM rubric_categories WHERE audit_type='planta' AND tag='S2';
INSERT INTO rubric_categories (audit_type, tag, label, sub, orden) VALUES ('planta', 'S3', 'S3 - Limpieza', 'Área, máquinas, muebles, objetos', 3);
INSERT INTO rubric_items (category_id, nombre, criterio_0, criterio_1, criterio_3, criterio_5, orden) SELECT id, '¿Se encuentra Agua, polvo, aceite o suciedad en el suelo?', 'El área está muy sucia', 'El área está con la suciedad lógica del sector', 'Toda el área está limpia.', 'Toda el área está limpia, con rutina clara de limpieza.', 1 FROM rubric_categories WHERE audit_type='planta' AND tag='S3';
INSERT INTO rubric_items (category_id, nombre, criterio_0, criterio_1, criterio_3, criterio_5, orden) SELECT id, 'Máquinas', 'Todas las máquinas están con aceites o suciedad.', 'Solo las máquinas críticas están limpias.', 'Todas las máquinas están limpias.', 'Toda el área está siempre limpia. Equipos y herramientas críticos con rutina clara de limpieza técnica.', 2 FROM rubric_categories WHERE audit_type='planta' AND tag='S3';
INSERT INTO rubric_items (category_id, nombre, criterio_0, criterio_1, criterio_3, criterio_5, orden) SELECT id, 'Utensilios de Limpieza (escobas/trapos/etc.)', 'No se sabe cuáles son los utensilios para limpiar tanto las máquinas como el sector.', 'No se encuentran los utensilios de limpieza en el área', 'Algunos utensilios de limpieza son guardados en el área', 'Todos los utensilios de limpieza que se necesitan se ubican en el área y están visualmente identificados', 3 FROM rubric_categories WHERE audit_type='planta' AND tag='S3';
INSERT INTO rubric_items (category_id, nombre, criterio_0, criterio_1, criterio_3, criterio_5, orden) SELECT id, '¿Son las actividades de limpieza compartidas por los trabajadores?', 'Nadie limpia, a menos que se le ordene', 'La limpieza se deja en manos de unos pocos a quienes interesa', 'La mayoría de la gente hace un esfuerzo por mantener limpio el lugar', 'La limpieza y el guardado de las herramientas son realizados sistemáticamente por todos con responsabilidades claras.', 4 FROM rubric_categories WHERE audit_type='planta' AND tag='S3';
INSERT INTO rubric_categories (audit_type, tag, label, sub, orden) VALUES ('planta', 'S4', 'S4 - Estandarización', 'Establecer normas y responsables', 4);
INSERT INTO rubric_items (category_id, nombre, criterio_0, criterio_1, criterio_3, criterio_5, orden) SELECT id, 'Estándares de Limpieza', 'Nadie sabe qué debería limpiarse ni quién debería hacerlo', 'Las áreas están informalmente asignadas para la limpieza', 'Las áreas están asignadas a personas, pero no se han establecido estándares de limpieza', 'Todos saben exactamente qué deben limpiar y a qué estándar de limpieza.', 1 FROM rubric_categories WHERE audit_type='planta' AND tag='S4';
INSERT INTO rubric_items (category_id, nombre, criterio_0, criterio_1, criterio_3, criterio_5, orden) SELECT id, 'Reuniones de 5S del Equipo', 'No se organizan reuniones de 5S', 'Ocasionalmente se organizan reuniones de 5S y no son productivas.', 'Se organizan reuniones de 5S, pero usualmente no son muy productivas.', 'Se organizan reuniones de 5S regularmente y son siempre muy productivas.', 2 FROM rubric_categories WHERE audit_type='planta' AND tag='S4';
INSERT INTO rubric_items (category_id, nombre, criterio_0, criterio_1, criterio_3, criterio_5, orden) SELECT id, 'Auditorías de 5S', 'No se conducen auditorías de 5S', 'A veces se realizan auditorías de 5S con poca participación del equipo', 'El equipo realiza auditorías de 5S regularmente, usualmente sin seguimiento', 'El equipo realiza auditorías de 5S regularmente y las utiliza para mejorar las 5S', 3 FROM rubric_categories WHERE audit_type='planta' AND tag='S4';
INSERT INTO rubric_items (category_id, nombre, criterio_0, criterio_1, criterio_3, criterio_5, orden) SELECT id, 'Registro de Acciones de Mejora para prevenir fuentes de contaminación, etc.', 'No existe registro de acciones y es muy raro que el equipo sugiera ideas', 'No existe registro de acciones, pero algunas ideas de mejora vienen del equipo', 'El registro de acciones está visualmente exhibido con ocasionales ideas del equipo', 'El registro de acciones está visualmente exhibido y el equipo sugiere ideas continuamente', 4 FROM rubric_categories WHERE audit_type='planta' AND tag='S4';
INSERT INTO rubric_categories (audit_type, tag, label, sub, orden) VALUES ('planta', 'S5', 'S5 - Mantener la Disciplina', 'Establecer rutinas y supervisar', 5);
INSERT INTO rubric_items (category_id, nombre, criterio_0, criterio_1, criterio_3, criterio_5, orden) SELECT id, 'Seguimiento de la gerencia', 'Sin soporte', 'Poco soporte, sólo esporádico (visitas, clientes, etc.)', 'Gerencia soporta las actividades de 5S, aunque sin recursos.', 'La Gerencia está comprometida con las actividades de 5S, las apoya & provee recursos a los esfuerzos del equipo', 1 FROM rubric_categories WHERE audit_type='planta' AND tag='S5';
INSERT INTO rubric_items (category_id, nombre, criterio_0, criterio_1, criterio_3, criterio_5, orden) SELECT id, 'Sentido de Pertenencia del Equipo', 'No hay sentido de pertenencia ni apoyo de los miembros del equipo para las actividades de 5S', 'Había entusiasmo inicial y sentido de pertenencia, pero parece estar desapareciendo', 'La mayoría de los miembros del equipo apoya las actividades de 5S', 'Todos los miembros del equipo tienen sentido de pertenencia y son entusiastas respecto de las 5S', 2 FROM rubric_categories WHERE audit_type='planta' AND tag='S5';
INSERT INTO rubric_items (category_id, nombre, criterio_0, criterio_1, criterio_3, criterio_5, orden) SELECT id, 'Indicadores Clave de Performance de 5S', 'No se han establecido KPI (objetivos) de las 5S', 'Se han establecido KPI para las 5S, pero sin gestión visual.', 'Los KPI de las 5S están establecidas, pero no siempre son actualizadas', 'Los KPI son visuales, se mantienen actualizados y se utilizan como herramientas de mejora por el equipo', 3 FROM rubric_categories WHERE audit_type='planta' AND tag='S5';
INSERT INTO rubric_items (category_id, nombre, criterio_0, criterio_1, criterio_3, criterio_5, orden) SELECT id, 'Integración de las 5S en el trabajo normal', 'Siempre toma un esfuerzo especial realizar cualquier actividad de 5S', 'Las 5S se implementan sólo si son monitoreadas de cerca por la Gerencia', 'La mayoría de los miembros del equipo tratan de integrar las actividades de 5S a sus rutinas diarias', 'Las 5S se han convertido en una parte normal del trabajo para todos los miembros del equipo', 4 FROM rubric_categories WHERE audit_type='planta' AND tag='S5';

-- 3b. Rubric: PANOL
INSERT INTO rubric_categories (audit_type, tag, label, sub, orden) VALUES ('panol', 'S1', 'S1 - Clasificar', 'Separar innecesarios', 1);
INSERT INTO rubric_items (category_id, nombre, criterio_0, criterio_1, criterio_3, criterio_5, orden) SELECT id, '¿Existen materiales, herramientas o equipos innecesarios?', 'No se han identificado ni eliminado.', 'Se ha hecho parcialmente.', 'Se ha hecho adecuadamente.', 'Se ha hecho de forma total y eficaz.', 1 FROM rubric_categories WHERE audit_type='panol' AND tag='S1';
INSERT INTO rubric_items (category_id, nombre, criterio_0, criterio_1, criterio_3, criterio_5, orden) SELECT id, '¿Existen áreas de almacenamiento para materiales o equipos obsoletos o dañados? (Zona roja)', 'No existen áreas de almacenamiento.', 'Existen, pero no están bien definidas.', 'Existen y están correctamente organizadas.', 'Existen, están correctamente organizadas y cuentan con un seguimiento a tiempo', 2 FROM rubric_categories WHERE audit_type='panol' AND tag='S1';
INSERT INTO rubric_items (category_id, nombre, criterio_0, criterio_1, criterio_3, criterio_5, orden) SELECT id, '¿Se encuentran desechos orgánicos, documentación, objetos personales, etc, en el área?', 'Se encuentran mas de 10 cosas innecesarias', 'Se encuentra menos de 10 de estas cosas innecesarias', 'Se encuentra menos de 3 de estas cosas innecesarias', 'No se encuentra ninguna cosa innecesaria', 3 FROM rubric_categories WHERE audit_type='panol' AND tag='S1';
INSERT INTO rubric_items (category_id, nombre, criterio_0, criterio_1, criterio_3, criterio_5, orden) SELECT id, '¿Se cuenta con un plan de retiro para desechar innecesarios?', 'No existe plan.', 'Existe plan y se realiza parcialmente con fechas vencidas', 'Existe plan y se realiza de forma adecuada', 'Existe plan y se actualiza según agenda', 4 FROM rubric_categories WHERE audit_type='panol' AND tag='S1';
INSERT INTO rubric_categories (audit_type, tag, label, sub, orden) VALUES ('panol', 'S2', 'S2 - Ordenar', 'Ubicación necesarios e identificar', 2);
INSERT INTO rubric_items (category_id, nombre, criterio_0, criterio_1, criterio_3, criterio_5, orden) SELECT id, '¿Las herramientas y materiales están organizados de acuerdo con su frecuencia de uso (por ejemplo, lo más utilizado en la parte delantera)?', 'No están organizados de acuerdo a la frecuencia de uso.', 'Están parcialmente organizados.', 'Están organizados adecuadamente, pero se puede mejorar.', 'Están organizados perfectamente, optimizando el espacio.', 1 FROM rubric_categories WHERE audit_type='panol' AND tag='S2';
INSERT INTO rubric_items (category_id, nombre, criterio_0, criterio_1, criterio_3, criterio_5, orden) SELECT id, '¿Se utilizan etiquetas, códigos, mínimos y máximos o colores para identificar correctamente los materiales?', 'No se utilizan etiquetas, códigos ni colores.', 'Se utilizan de forma limitada y con una gestión visual deficiente.', 'Se utilizan adecuadamente en la mayoría de los casos.', 'Se utilizan eficientemente y en todos los materiales.', 2 FROM rubric_categories WHERE audit_type='panol' AND tag='S2';
INSERT INTO rubric_items (category_id, nombre, criterio_0, criterio_1, criterio_3, criterio_5, orden) SELECT id, '¿Existen estantes, cajas o contenedores adecuados para almacenar los materiales de manera ordenada?', 'No existen estantes ni contenedores adecuados.', 'Existen en algunos, pero no son adecuados.', 'Existen en algunos y son adecuados, aunque mejorables.', 'Existen en todos los que se necesita y son perfectamente adecuados para el orden.', 3 FROM rubric_categories WHERE audit_type='panol' AND tag='S2';
INSERT INTO rubric_items (category_id, nombre, criterio_0, criterio_1, criterio_3, criterio_5, orden) SELECT id, '¿Se tiene un inventario claro y preciso de todos los materiales almacenados en el área? Puede ser físico o digital', 'No se tiene inventario.', 'El inventario es parcial y no preciso.', 'El inventario es preciso, pero con algunas deficiencias.', 'El inventario es claro, preciso y actualizado.', 4 FROM rubric_categories WHERE audit_type='panol' AND tag='S2';
INSERT INTO rubric_categories (audit_type, tag, label, sub, orden) VALUES ('panol', 'S3', 'S3 - Limpieza', 'Área, máquinas, muebles, objetos', 3);
INSERT INTO rubric_items (category_id, nombre, criterio_0, criterio_1, criterio_3, criterio_5, orden) SELECT id, '¿El área, las herramientas, equipos y materiales están libres de residuos o manchas?', 'No están libres de residuos ni manchas.', 'Están parcialmente libres de residuos.', 'Están mayormente libres de residuos, pero con algunas áreas por mejorar.', 'Están totalmente libres de residuos y manchas.', 1 FROM rubric_categories WHERE audit_type='panol' AND tag='S3';
INSERT INTO rubric_items (category_id, nombre, criterio_0, criterio_1, criterio_3, criterio_5, orden) SELECT id, '¿Se realiza una limpieza diaria de las áreas de trabajo?', 'No se realiza limpieza diaria.', 'Se realiza esporádicamente.', 'Se realiza casi todos los días solo por algunas personas.', 'Todo el personal realiza todos los días de manera consistente.', 2 FROM rubric_categories WHERE audit_type='panol' AND tag='S3';
INSERT INTO rubric_items (category_id, nombre, criterio_0, criterio_1, criterio_3, criterio_5, orden) SELECT id, '¿Existen procedimientos de limpieza específicos para el área?', 'No existen procedimientos.', 'Existen, pero no son específicos ni claros.', 'Existen procedimientos adecuados, pero mejorables.', 'Existen procedimientos claros, detallados y efectivos.', 3 FROM rubric_categories WHERE audit_type='panol' AND tag='S3';
INSERT INTO rubric_items (category_id, nombre, criterio_0, criterio_1, criterio_3, criterio_5, orden) SELECT id, '¿El personal está capacitado en las normas de limpieza y mantenimiento del área?', 'El personal no está capacitado.', 'Algunas personas solo fueron capacitados', 'Todo el personal está completamente capacitado.', 'El personal está completamente capacitado, aplica las normas y tienen un plan de entrenamiento para los nuevos ingresantes.', 4 FROM rubric_categories WHERE audit_type='panol' AND tag='S3';
INSERT INTO rubric_categories (audit_type, tag, label, sub, orden) VALUES ('panol', 'S4', 'S4 - Estandarización', 'Establecer normas y responsables', 4);
INSERT INTO rubric_items (category_id, nombre, criterio_0, criterio_1, criterio_3, criterio_5, orden) SELECT id, '¿Existen normas y procedimientos documentados para la implementación de las 5S en el área?', 'No existen normas ni procedimientos documentados.', 'Existen parcialmente documentados.', 'Existen documentados y se siguen en su mayoría.', 'Existen normas y procedimientos claros, documentados y seguidos correctamente.', 1 FROM rubric_categories WHERE audit_type='panol' AND tag='S4';
INSERT INTO rubric_items (category_id, nombre, criterio_0, criterio_1, criterio_3, criterio_5, orden) SELECT id, '¿El personal conoce y sigue los procedimientos establecidos para cada una de las 5S?', 'El personal no conoce ni sigue los procedimientos.', 'El personal conoce parcialmente, pero no sigue todos los procedimientos.', 'El personal conoce sus procedimientos y sigue la mayoría de los mismos.', 'El personal sigue todos los procedimientos de manera consistente, observándose que tienen mejoras al estándar.', 2 FROM rubric_categories WHERE audit_type='panol' AND tag='S4';
INSERT INTO rubric_items (category_id, nombre, criterio_0, criterio_1, criterio_3, criterio_5, orden) SELECT id, '¿El área tiene un mapa o plano que indique la ubicación de los materiales y equipos?', 'No existe mapa ni plano.', 'Existe, pero no es claro ni actualizado.', 'Existe y es adecuado, pero podría mejorarse.', 'Existe y es claro, preciso y útil.', 3 FROM rubric_categories WHERE audit_type='panol' AND tag='S4';
INSERT INTO rubric_items (category_id, nombre, criterio_0, criterio_1, criterio_3, criterio_5, orden) SELECT id, '¿Existen formularios de control para la gestión de materiales y equipos? (ej check list de maquinas / autoelevadores, etc)', 'No existen formularios de control.', 'Existen, pero no son adecuados ni completos.', 'Existen formularios adecuados, pero con algunas deficiencias.', 'Existen formularios eficientes, claros y completos.', 4 FROM rubric_categories WHERE audit_type='panol' AND tag='S4';
INSERT INTO rubric_categories (audit_type, tag, label, sub, orden) VALUES ('panol', 'S5', 'S5 - Mantener la Disciplina', 'Establecer rutinas y supervisar', 5);
INSERT INTO rubric_items (category_id, nombre, criterio_0, criterio_1, criterio_3, criterio_5, orden) SELECT id, '¿Se realizan auditorías internas periódicas para asegurar que se siguen las normas de las 5S?', 'No se conducen auditorías de 5S.', 'A veces se realizan auditorías de 5S con poca participación del equipo', 'El equipo realiza auditorías de 5S regularmente, usualmente sin seguimiento', 'El equipo realiza auditorías de 5S regularmente y las utiliza para mejorar las 5S', 1 FROM rubric_categories WHERE audit_type='panol' AND tag='S5';
INSERT INTO rubric_items (category_id, nombre, criterio_0, criterio_1, criterio_3, criterio_5, orden) SELECT id, 'Sentido de pertenencia con las 5S', 'No hay sentido de pertenencia ni apoyo de los miembros del equipo para las actividades de 5S', 'Había entusiasmo inicial y sentido de pertenencia, pero parece estar desapareciendo', 'La mayoría de los miembros del equipo apoya las actividades de 5S', 'Todos los miembros del equipo tienen sentido de pertenencia y son entusiastas respecto de las 5S', 2 FROM rubric_categories WHERE audit_type='panol' AND tag='S5';
INSERT INTO rubric_items (category_id, nombre, criterio_0, criterio_1, criterio_3, criterio_5, orden) SELECT id, 'El personal realiza mejoras continuas e informa sobre cualquier desviación de las 5S de forma oportuna', 'El equipo no realiza mejoras ni informa las desviaciones.', 'El equipo realiza algunas mejoras esporádicas y avisa muy tarde una vez ocurrido el evento.', 'El equipo informa oportunamente los eventos aunque sus mejoras se caen en el tiempo.', 'El equipo realiza mejoras continuas y efectivas en todas las áreas y sus informes están muy bien detallado.', 3 FROM rubric_categories WHERE audit_type='panol' AND tag='S5';
INSERT INTO rubric_items (category_id, nombre, criterio_0, criterio_1, criterio_3, criterio_5, orden) SELECT id, 'Seguimiento de la gerencia', 'Sin soporte', 'Poco soporte, sólo esporádico (visitas, clientes, etc.)', 'Gerencia soporta las actividades de 5S, aunque sin recursos.', 'La Gerencia está comprometida con las actividades de 5S, las apoya & provee recursos a los esfuerzos del equipo', 4 FROM rubric_categories WHERE audit_type='panol' AND tag='S5';

-- 3c. Rubric: OFICINA
INSERT INTO rubric_categories (audit_type, tag, label, sub, orden) VALUES ('oficina', 'S1', 'S1 - Clasificar', 'Separar innecesarios', 1);
INSERT INTO rubric_items (category_id, nombre, criterio_0, criterio_1, criterio_3, criterio_5, orden) SELECT id, '"Despeje de Mobiliarios y Equipos" innecesarios', 'El área nunca ha sido despejada de mobiliarios y equipamientos innecesarios', 'Hay mobiliarios y equipos obsoletos, rotos o innecesarios en el área', 'Hay mobiliarios y equipos obsoletos, rotos o innecesarios, pero cuentan con plan para su retiro', 'Sólo están las mobiliarios y equipos necesarios y en condiciones en el área', 1 FROM rubric_categories WHERE audit_type='oficina' AND tag='S1';
INSERT INTO rubric_items (category_id, nombre, criterio_0, criterio_1, criterio_3, criterio_5, orden) SELECT id, 'Información y Documentos Impresos', 'El área nunca ha sido despejada de Información innecesaria', 'Existe Información innecesaria o excesiva en el área', 'Raramente se encuentra Información innecesaria en el área', 'Solo la Información necesaria se encuentra en el área de trabajo', 2 FROM rubric_categories WHERE audit_type='oficina' AND tag='S1';
INSERT INTO rubric_items (category_id, nombre, criterio_0, criterio_1, criterio_3, criterio_5, orden) SELECT id, 'Despeje de Elementos y Consumibles', 'El área nunca ha sido despejada de elementos innecesarios', 'Existen Elementos innecesarios, excesivos o faltantes en el área', 'Raramente se encuentran elementos innecesario en el área', 'Solo los elementos necesarios se encuentra en el área de trabajo', 3 FROM rubric_categories WHERE audit_type='oficina' AND tag='S1';
INSERT INTO rubric_items (category_id, nombre, criterio_0, criterio_1, criterio_3, criterio_5, orden) SELECT id, 'Seguridad — Riesgos', '"Vías de circulación obstaculizadas. Existen cables u otros elementos que puedan generar riesgos"', '', 'Esfuerzo leve por mantener Vías de circ. libres de obtáculos. Se han identificados elementos de riesgos (3 puntos)', 'Vías de circulación totalmente libres. No existren elementos o instalaciones que puedan generar peligros', 4 FROM rubric_categories WHERE audit_type='oficina' AND tag='S1';
INSERT INTO rubric_categories (audit_type, tag, label, sub, orden) VALUES ('oficina', 'S2', 'S2 - Ordenar', 'Ubicación necesarios e identificar', 2);
INSERT INTO rubric_items (category_id, nombre, criterio_0, criterio_1, criterio_3, criterio_5, orden) SELECT id, 'Orden de Mobiliario y Equipos', 'Nunca se ha ordenado el mobiliario y equipos', 'Hay una distribución establecida para los mismos, pero no se respeta', 'Ocasionalmente se encuentra el mobiliario y equipos desordenados', 'Siempre se encuentra el mobiliario y equipos en orden establecido', 1 FROM rubric_categories WHERE audit_type='oficina' AND tag='S2';
INSERT INTO rubric_items (category_id, nombre, criterio_0, criterio_1, criterio_3, criterio_5, orden) SELECT id, 'Orden de Información y Documentos Impresos', 'Nunca se ha ordenado la información y documentos', 'Hay una acción establecida para ordenar los archivos, pero el esfuerzo por respetarlo es leve', 'Ocasionalmente se encuentra información y documentos desordenados', 'Siempre se encuentra información y documentos en orden en biblioteca y espacios comunes', 2 FROM rubric_categories WHERE audit_type='oficina' AND tag='S2';
INSERT INTO rubric_items (category_id, nombre, criterio_0, criterio_1, criterio_3, criterio_5, orden) SELECT id, 'Orden de Elementos e Insumos', 'Distancias excesivas a recorrer por los usuarios para buscar elementos de uso frecuente o diario', 'Las distancias a por los usuarios para buscar elementos puntuales son excesivas', 'Los elementos más requeridos se encuentran ubicados cerca del lugar donde se los usa', 'Todos los elementos se encuentran cerca del lugar donde se las usa y están identificados', 3 FROM rubric_categories WHERE audit_type='oficina' AND tag='S2';
INSERT INTO rubric_items (category_id, nombre, criterio_0, criterio_1, criterio_3, criterio_5, orden) SELECT id, 'Seguridad', 'No se cuenta con elementos de seguridad', '', 'Solo algunos de los elementos de seguridad están al alcance de los usuarios (3 puntos)', 'Los elementos de seguridad están en condiciones, señalizados y al alcance de todos.', 4 FROM rubric_categories WHERE audit_type='oficina' AND tag='S2';
INSERT INTO rubric_categories (audit_type, tag, label, sub, orden) VALUES ('oficina', 'S3', 'S3 - Limpieza', 'Área, máquinas, muebles, objetos', 3);
INSERT INTO rubric_items (category_id, nombre, criterio_0, criterio_1, criterio_3, criterio_5, orden) SELECT id, 'Limpieza del Área', 'Sala de reuniones, otros espacios, se encuentran sucios', 'Sala de reuniones, otros espacios, no se limpian frecuentemente', 'Sala de reuniones, otros espacios, se limpian frecuentemente', 'Sala de reuniones, otros espacios, cuentan con un programa de limpieza conocido por todos', 1 FROM rubric_categories WHERE audit_type='oficina' AND tag='S3';
INSERT INTO rubric_items (category_id, nombre, criterio_0, criterio_1, criterio_3, criterio_5, orden) SELECT id, 'Plan de Limpieza 5''S', 'No existe plan de limpieza', 'Existe plan de limpieza pero no es conocido por todos', 'El plan de limpieza es conocido por todos y se cumple parcialmente', 'El plan de limpieza es conocido y cumplido por todas las personas (5''S)', 2 FROM rubric_categories WHERE audit_type='oficina' AND tag='S3';
INSERT INTO rubric_items (category_id, nombre, criterio_0, criterio_1, criterio_3, criterio_5, orden) SELECT id, 'Ubicación de Elementos de Limpieza (escobas/trapos/etc.)', 'No se encuentran los elementos de limpieza en el área', '', 'Algunos elementos de limpieza son guardados en el área (3 puntos)', 'Todos los elementos de limpieza que se necesitan se ubican en el área y están visualmente identificados', 3 FROM rubric_categories WHERE audit_type='oficina' AND tag='S3';
INSERT INTO rubric_items (category_id, nombre, criterio_0, criterio_1, criterio_3, criterio_5, orden) SELECT id, 'Limpieza Diaria', 'Nadie procura mantener el área limpia', 'Solo se limpia por orden del supervisor', 'Esfuerzos leves por solo algunas personas y los demas solo por orden del supervisor', 'Area en condiciones. Todos se preocupan por mantener el área limpia', 4 FROM rubric_categories WHERE audit_type='oficina' AND tag='S3';
INSERT INTO rubric_categories (audit_type, tag, label, sub, orden) VALUES ('oficina', 'S4', 'S4 - Estandarización', 'Establecer normas y responsables', 4);
INSERT INTO rubric_items (category_id, nombre, criterio_0, criterio_1, criterio_3, criterio_5, orden) SELECT id, 'Estándares en Mobiliario y Equipos, Elementos e Insumos', 'No están establecidos los estándares', 'Solo algunos espacios y elementos se encuentran demarcados y rotulados', 'Todos los espacios y elementos se encuentran demarcados, rotulados y se utiliza gestión visual', 'Los estándares se han establecido de manera tal que el criterio es unequívoco', 1 FROM rubric_categories WHERE audit_type='oficina' AND tag='S4';
INSERT INTO rubric_items (category_id, nombre, criterio_0, criterio_1, criterio_3, criterio_5, orden) SELECT id, 'Orden de Información y Documentos Impresos', 'No están establecidos los estándares', 'Solo algunos documentos poseen identificación', 'Las carpetas se encuentran con un orden establecido, y se sabe claramente lo que contienen', 'Los estándares se han establecido de manera tal que el criterio es unequívoco', 2 FROM rubric_categories WHERE audit_type='oficina' AND tag='S4';
INSERT INTO rubric_items (category_id, nombre, criterio_0, criterio_1, criterio_3, criterio_5, orden) SELECT id, 'Responsabilidad/Estándares de Limpieza', 'Nadie sabe qué debería limpiarse ni quién debería hacerlo', 'Las áreas están informalmente asignadas para la limpieza', 'Las áreas están asignadas a personas, pero no se han establecido estándares de limpieza', 'Todos saben exactamente qué deben limpiar y a qué estándar', 3 FROM rubric_categories WHERE audit_type='oficina' AND tag='S4';
INSERT INTO rubric_items (category_id, nombre, criterio_0, criterio_1, criterio_3, criterio_5, orden) SELECT id, 'Reuniones de 5S del Equipo y auditorías de 5S', 'No se organizan reuniones de 5S ni se conducen auditorías de 5S', 'A veces se realizan auditorías de 5S con poca participación del equipo.', 'Se realizan reuniones y auditorías de 5S regularmente, usualmente sin seguimiento', 'Las reuniones y auditorías de 5S regularmente se utilizan para mejorar. Plan a largo plazo', 4 FROM rubric_categories WHERE audit_type='oficina' AND tag='S4';
INSERT INTO rubric_categories (audit_type, tag, label, sub, orden) VALUES ('oficina', 'S5', 'S5 - Mantener la Disciplina', 'Establecer rutinas y supervisar', 5);
INSERT INTO rubric_items (category_id, nombre, criterio_0, criterio_1, criterio_3, criterio_5, orden) SELECT id, 'Apoyo de la Gerencia', 'Sin soporte por parte de la gerencia en las actividades de 5S', 'Poco soporte, sólo esporádico (visitas, clientes, etc.)', 'Gerencia apoya actividades 5S y reconoce al personal que participa en las actividades, baja prioridad', 'Compromiso con las actividades de 5S, las apoya siempre & provee recursos a los esfuerzos del equipo', 1 FROM rubric_categories WHERE audit_type='oficina' AND tag='S5';
INSERT INTO rubric_items (category_id, nombre, criterio_0, criterio_1, criterio_3, criterio_5, orden) SELECT id, 'Respeto por los Estándares', 'No se respetan los estándares, no hay compromiso. "1/2/3/4S"', '', '"El cumplimiento con los estándares es parcial, encontrándose algunos casos de falla. El nivel de compromiso es bajo. (3 puntos)"', 'Se respetan todos los estándares fijados con un alto nivel de compromiso.', 2 FROM rubric_categories WHERE audit_type='oficina' AND tag='S5';
INSERT INTO rubric_items (category_id, nombre, criterio_0, criterio_1, criterio_3, criterio_5, orden) SELECT id, 'Indicadores Clave de Performance de 5S', 'No se han establecido KPI (objetivos) de las 5S', 'Se han establecido KPI para las 5S, pero usualmente no tienen seguimiento y no son visuales', 'Los KPI de las 5S están establecidas, pero no siempre son actualizadas', 'Los KPI son visuales, se mantienen actualizados y se utilizan como herramientas de mejora', 3 FROM rubric_categories WHERE audit_type='oficina' AND tag='S5';
INSERT INTO rubric_items (category_id, nombre, criterio_0, criterio_1, criterio_3, criterio_5, orden) SELECT id, 'Integración de las 5S en el Trabajo Normal', 'Siempre toma un esfuerzo especial realizar cualquier actividad de 5S', 'Las 5S se implementan sólo si son monitoreadas de cerca por la Gerencia', 'La mayoría del equipo tratan de integrar las actividades de 5S a sus rutinas diarias', 'Las 5S se han convertido en una parte normal del trabajo para todos los miembros del equipo', 4 FROM rubric_categories WHERE audit_type='oficina' AND tag='S5';

-- 4. Objetivos mensuales 2026 — Planta (lineal 30 -> 75)
INSERT INTO monthly_targets (audit_type, anio, mes, objetivo) VALUES
('planta', 2026, 1, 30.0),
('planta', 2026, 2, 34.1),
('planta', 2026, 3, 38.2),
('planta', 2026, 4, 42.3),
('planta', 2026, 5, 46.4),
('planta', 2026, 6, 50.5),
('planta', 2026, 7, 54.5),
('planta', 2026, 8, 58.6),
('planta', 2026, 9, 62.7),
('planta', 2026, 10, 66.8),
('planta', 2026, 11, 70.9),
('planta', 2026, 12, 75.0);
-- Pañol / Oficina: sin objetivo definido todavía (Dashboard muestra estado vacío)
